name: Deploy to staging

on:
  push:
    branches: [main]
jobs:
  redeploy_everything:
     runs-on: ubuntu-latest
     name: Deploying everything to the staging cluster
     steps:
       - run: |
            echo "${{secrets.SSH_PRIVATE_KEY}}" &> ~/ssh_key
            mkdir -p /home/runner/.ssh
            touch /home/runner/.ssh/known_hosts
            ls -l /home/runner/.ssh/known_hosts
            echo "${{secrets.SSH_KNOWN_HOSTS}}" &> /home/runner/.ssh/known_hosts
            ssh -i ~/ssh_key root@142.93.247.236
            cd week-deployment/Devops/bms && git pull
            pnpm install
            pnpm run build
            pm2 restart http-server
            pm2 restart nextjs
            pm2 restart web-socket



